using System;
using System.Text;
using System.Windows.Forms;
using MongoDB.Bson;
using MongoDB.Driver;
using System.Linq;

namespace TaskManagementApp
{
    public partial class ReportForm : Form
    {
        private IMongoDatabase _db;
        private IMongoCollection<BsonDocument> _tasks;
        private IMongoCollection<BsonDocument> _reports;
        private IMongoCollection<BsonDocument> _users;
        private IMongoCollection<BsonDocument> _auditLogs;

        public ReportForm()
        {
            InitializeComponent();

            try
            {
                _db = MongoConnection.GetDatabase();
                _tasks = _db.GetCollection<BsonDocument>("Tasks");
                _reports = _db.GetCollection<BsonDocument>("Reports");
                _users = _db.GetCollection<BsonDocument>("Users");
                _auditLogs = _db.GetCollection<BsonDocument>("AuditLogs");
                LoadUsers();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error connecting to database: " + ex.Message);
            }
        }

        private void LoadUsers()
        {
            try
            {
                var users = _users.Find(new BsonDocument()).ToList();
                cmbUser.Items.Clear();
                cmbUser.Items.Add("All Users");

                foreach (var user in users)
                {
                    string userID = user.GetValue("UserID", "").ToString();
                    string username = user.GetValue("Username", "").ToString();
                    cmbUser.Items.Add($"{userID} - {username}");
                }

                cmbUser.SelectedIndex = 0;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading users: " + ex.Message);
            }
        }

        private void btnGenerate_Click(object sender, EventArgs e)
        {
            try
            {
                string selectedUser = cmbUser.SelectedItem.ToString();
                ObjectId? userObjectId = null;

                if (selectedUser != "All Users")
                {
                    string userID = selectedUser.Split('-')[0].Trim();
                    var userFilter = Builders<BsonDocument>.Filter.Eq("UserID", userID);
                    var user = _users.Find(userFilter).FirstOrDefault();

                    if (user != null && user.Contains("_id"))
                    {
                        userObjectId = user["_id"].AsObjectId;
                    }
                }

                var report = GenerateReport(userObjectId);
                txtReport.Text = report;

                SaveReport(selectedUser, report);
                LogAudit(LoginForm.LoggedInUserID, "Generate Report", $"Generated report for: {selectedUser}");

                MessageBox.Show("Report generated successfully!");
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error generating report: " + ex.Message);
            }
        }

        private string GenerateReport(ObjectId? userObjectId)
        {
            StringBuilder report = new StringBuilder();
            report.AppendLine("═══════════════════════════════════════════════");
            report.AppendLine("          TASK MANAGEMENT SYSTEM REPORT");
            report.AppendLine("═══════════════════════════════════════════════");
            report.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            report.AppendLine($"Generated By: {LoginForm.LoggedInUsername}");

            if (userObjectId.HasValue)
            {
                report.AppendLine($"User Filter: {userObjectId.Value}");
            }
            else
            {
                report.AppendLine("User Filter: All Users");
            }

            report.AppendLine("═══════════════════════════════════════════════\n");

            // Get tasks
            FilterDefinition<BsonDocument> filter;
            if (userObjectId.HasValue)
            {
                filter = Builders<BsonDocument>.Filter.Eq("UserID", userObjectId.Value);
            }
            else
            {
                filter = Builders<BsonDocument>.Filter.Empty;
            }

            var tasks = _tasks.Find(filter).ToList();

            // Overall Statistics
            int totalTasks = tasks.Count;
            int pendingTasks = tasks.Count(t => t.GetValue("TaskStatus", "").ToString() == "Pending");
            int inProgressTasks = tasks.Count(t => t.GetValue("TaskStatus", "").ToString() == "In Progress");
            int completedTasks = tasks.Count(t => t.GetValue("TaskStatus", "").ToString() == "Completed");

            report.AppendLine("OVERALL STATISTICS:");
            report.AppendLine("───────────────────────────────────────────────");
            report.AppendLine($"Total Tasks:        {totalTasks}");
            report.AppendLine($"Pending:            {pendingTasks} ({GetPercentage(pendingTasks, totalTasks)}%)");
            report.AppendLine($"In Progress:        {inProgressTasks} ({GetPercentage(inProgressTasks, totalTasks)}%)");
            report.AppendLine($"Completed:          {completedTasks} ({GetPercentage(completedTasks, totalTasks)}%)");
            report.AppendLine($"Completion Rate:    {GetPercentage(completedTasks, totalTasks)}%");
            report.AppendLine();

            // Step Statistics
            int totalSteps = 0;
            int completedSteps = 0;

            foreach (var task in tasks)
            {
                if (task.Contains("Steps") && task["Steps"].IsBsonArray)
                {
                    var steps = task["Steps"].AsBsonArray;
                    totalSteps += steps.Count;

                    foreach (var step in steps)
                    {
                        if (step.AsBsonDocument.GetValue("StepStatus", "").ToString() == "Completed")
                        {
                            completedSteps++;
                        }
                    }
                }
            }

            report.AppendLine("STEP COMPLETION:");
            report.AppendLine("───────────────────────────────────────────────");
            report.AppendLine($"Total Steps:        {totalSteps}");
            report.AppendLine($"Completed Steps:    {completedSteps}");
            report.AppendLine($"Step Completion:    {GetPercentage(completedSteps, totalSteps)}%");
            report.AppendLine();

            // Task Details
            if (tasks.Count > 0)
            {
                report.AppendLine("TASK DETAILS:");
                report.AppendLine("───────────────────────────────────────────────");

                foreach (var task in tasks)
                {
                    int taskSteps = 0;
                    int taskCompletedSteps = 0;

                    if (task.Contains("Steps") && task["Steps"].IsBsonArray)
                    {
                        var steps = task["Steps"].AsBsonArray;
                        taskSteps = steps.Count;
                        taskCompletedSteps = steps.Count(s => s.AsBsonDocument.GetValue("StepStatus", "").ToString() == "Completed");
                    }

                    report.AppendLine($"\nTask ID: {task.GetValue("TaskID", "")}");
                    report.AppendLine($"Title: {task.GetValue("Title", "")}");
                    report.AppendLine($"Assigned To: {task.GetValue("UserID", "")}");
                    report.AppendLine($"Status: {task.GetValue("TaskStatus", "")}");
                    report.AppendLine($"Steps: {taskCompletedSteps}/{taskSteps} completed");
                }
            }

            report.AppendLine("\n═══════════════════════════════════════════════");
            report.AppendLine("                  END OF REPORT");
            report.AppendLine("═══════════════════════════════════════════════");

            return report.ToString();
        }

        private double GetPercentage(int value, int total)
        {
            if (total == 0) return 0;
            return Math.Round((double)value / total * 100, 1);
        }

        private void SaveReport(string userFilter, string reportContent)
        {
            try
            {
                var report = new BsonDocument
                {
                    { "ReportID", "RPT" + DateTime.Now.ToString("yyyyMMddHHmmss") },
                    { "UserFilter", userFilter },
                    { "ProgressData", reportContent },
                    { "GeneratedDate", DateTime.Now }
                };

                _reports.InsertOne(report);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error saving report: " + ex.Message);
            }
        }

        private void btnExport_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(txtReport.Text))
            {
                MessageBox.Show("Please generate a report first.");
                return;
            }

            try
            {
                SaveFileDialog saveDialog = new SaveFileDialog();
                saveDialog.Filter = "Text Files (*.txt)|*.txt";
                saveDialog.FileName = $"TaskReport_{DateTime.Now:yyyyMMddHHmmss}.txt";

                if (saveDialog.ShowDialog() == DialogResult.OK)
                {
                    System.IO.File.WriteAllText(saveDialog.FileName, txtReport.Text);
                    MessageBox.Show("Report exported successfully!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error exporting report: " + ex.Message);
            }
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void LogAudit(string userID, string action, string details)
        {
            try
            {
                var log = new BsonDocument
                {
                    { "LogID", Guid.NewGuid().ToString() },
                    { "UserID", userID },
                    { "Action", action },
                    { "Details", details },
                    { "Timestamp", DateTime.Now }
                };

                _auditLogs.InsertOne(log);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Audit log error: " + ex.Message);
            }
        }
    }
}