using DnsClient.Protocol;
using MongoDB.Driver;
using System;
using System.ComponentModel.Composition.Primitives;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using TaskManagementApp.Models;

namespace TaskManagementApp
{
    public partial class ReportForm : Form
    {
        private IMongoCollection<TaskItem> tasksCollection;
        private IMongoCollection<Report> reportsCollection;
        private IMongoCollection<User> usersCollection;
        private IMongoCollection<AuditLog> auditCollection;

        public ReportForm()
        {
            InitializeComponent();
            var db = MongoConnection.GetDatabase();
            tasksCollection = db.GetCollection<TaskItem>("Tasks");
            reportsCollection = db.GetCollection<Report>("Reports");
            usersCollection = db.GetCollection<User>("Users");
            auditCollection = db.GetCollection<AuditLog>("AuditLogs");
            LoadUsers();
        }

        private void LoadUsers()
        {
            try
            {
                var users = usersCollection.Find(_ => true).ToList();
                cmbUser.Items.Clear();
                cmbUser.Items.Add("All Users");
                foreach (var user in users)
                {
                    cmbUser.Items.Add($"{user.UserID} - {user.Username}");
                }
                cmbUser.SelectedIndex = 0;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading users: " + ex.Message, "Error",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnGenerate_Click(object sender, EventArgs e)
        {
            try
            {
                string selectedUser = cmbUser.SelectedItem.ToString();
                string userID = null;

                if (selectedUser != "All Users")
                {
                    userID = selectedUser.Split('-')[0].Trim();
                }

                var report = GenerateReport(userID);
                txtReport.Text = report;

                // Save report to database
                SaveReport(userID, report);

                // Log audit
                LogAudit(LoginForm.LoggedInUserID, null, null, "Generate Report");

                MessageBox.Show("Report generated successfully!", "Success",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error generating report: " + ex.Message, "Error",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private string GenerateReport(string userID)
        {
            StringBuilder report = new StringBuilder();
            report.AppendLine("═══════════════════════════════════════════════");
            report.AppendLine("          TASK MANAGEMENT SYSTEM REPORT");
            report.AppendLine("═══════════════════════════════════════════════");
            report.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            report.AppendLine($"Generated By: {LoginForm.LoggedInUsername}");

            if (userID != null)
            {
                report.AppendLine($"User Filter: {userID}");
            }
            else
            {
                report.AppendLine("User Filter: All Users");
            }

            report.AppendLine("═══════════════════════════════════════════════\n");

            // Get tasks
            FilterDefinition<TaskItem> filter;
            if (userID != null)
            {
                filter = Builders<TaskItem>.Filter.Eq(t => t.UserID, userID);
            }
            else
            {
                filter = Builders<TaskItem>.Filter.Empty;
            }

            var tasks = tasksCollection.Find(filter).ToList();

            // Overall Statistics
            int totalTasks = tasks.Count;
            int pendingTasks = tasks.Count(t => t.Task_Status == "Pending");
            int inProgressTasks = tasks.Count(t => t.Task_Status == "In Progress");
            int completedTasks = tasks.Count(t => t.Task_Status == "Completed");

            report.AppendLine("OVERALL STATISTICS:");
            report.AppendLine("───────────────────────────────────────────────");
            report.AppendLine($"Total Tasks:        {totalTasks}");
            report.AppendLine($"Pending:            {pendingTasks} ({GetPercentage(pendingTasks, totalTasks)}%)");
            report.AppendLine($"In Progress:        {inProgressTasks} ({GetPercentage(inProgressTasks, totalTasks)}%)");
            report.AppendLine($"Completed:          {completedTasks} ({GetPercentage(completedTasks, totalTasks)}%)");
            report.AppendLine($"Completion Rate:    {GetPercentage(completedTasks, totalTasks)}%");
            report.AppendLine();

            // Step Statistics
            int totalSteps = tasks.Sum(t => t.Steps?.Count ?? 0);
            int completedSteps = tasks.Sum(t => t.Steps?.Count(s => s.StepStatus == "Completed") ?? 0);

            report.AppendLine("STEP COMPLETION:");
            report.AppendLine("───────────────────────────────────────────────");
            report.AppendLine($"Total Steps:        {totalSteps}");
            report.AppendLine($"Completed Steps:    {completedSteps}");
            report.AppendLine($"Step Completion:    {GetPercentage(completedSteps, totalSteps)}%");
            report.AppendLine();

            // Task Details
            if (tasks.Count > 0)
            {
                report.AppendLine("TASK DETAILS:");
                report.AppendLine("───────────────────────────────────────────────");

                foreach (var task in tasks)
                {
                    int taskSteps = task.Steps?.Count ?? 0;
                    int taskCompletedSteps = task.Steps?.Count(s => s.StepStatus == "Completed") ?? 0;

                    report.AppendLine($"\nTask ID: {task.TaskID}");
                    report.AppendLine($"Title: {task.Title}");
                    report.AppendLine($"Assigned To: {task.UserID}");
                    report.AppendLine($"Status: {task.Task_Status}");
                    report.AppendLine($"Steps: {taskCompletedSteps}/{taskSteps} completed");
                    if (task.DueDate.HasValue)
                    {
                        report.AppendLine($"Due Date: {task.DueDate.Value:yyyy-MM-dd}");
                    }
                }
            }

            report.AppendLine("\n═══════════════════════════════════════════════");
            report.AppendLine("                  END OF REPORT");
            report.AppendLine("═══════════════════════════════════════════════");

            return report.ToString();
        }

        private double GetPercentage(int value, int total)
        {
            if (total == 0) return 0;
            return Math.Round((double)value / total * 100, 1);
        }

        private void SaveReport(string userID, string reportContent)
        {
            try
            {
                var report = new Report
                {
                    ReportID = "RPT" + DateTime.Now.ToString("yyyyMMddHHmmss"),
                    TaskID = userID ?? "ALL",
                    ProgressData = reportContent,
                    GeneratedDate = DateTime.Now
                };

                reportsCollection.InsertOne(report);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error saving report: " + ex.Message);
            }
        }

        private void btnExport_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(txtReport.Text))
            {
                MessageBox.Show("Please generate a report first.", "Warning",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                SaveFileDialog saveDialog = new SaveFileDialog();
                saveDialog.Filter = "Text Files (*.txt)|*.txt";
                saveDialog.FileName = $"TaskReport_{DateTime.Now:yyyyMMddHHmmss}.txt";

                if (saveDialog.ShowDialog() == DialogResult.OK)
                {
                    System.IO.File.WriteAllText(saveDialog.FileName, txtReport.Text);
                    MessageBox.Show("Report exported successfully!", "Success",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error exporting report: " + ex.Message, "Error",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void LogAudit(string userID, string taskID, string stepID, string action)
        {
            try
            {
                var log = new AuditLog
                {
                    LogID = Guid.NewGuid().ToString(),
                    UserID = userID,
                    TaskID = taskID,
                    StepID = stepID,
                    Action = action,
                    Timestamp = DateTime.Now
                };

                auditCollection.InsertOne(log);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Audit log error: " + ex.Message);
            }
        }
    }
}